name: Android CI

on:
  workflow_dispatch:
jobs:
  lint:
    name: Linting debug variant
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
        cache: 'gradle'
    - name: Test command
      run: echo hello world!
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: chmod
      run: chmod +x ./gradlew
    - name: lintDebug
      run: ./gradlew lintDebug



